name: Build
on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '*.md'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - '*.md'
permissions:
  contents: write
jobs:
  build:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Get short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
      - name: Build Plugin
        uses: gradle/gradle-build-action@v3
        with:
          arguments: build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: RedPacket-${{ env.SHORT_SHA }}
          path: build/libs/*.jar
          if-no-files-found: error
